### Create a new post
POST http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UyNDNlZGVkYTdmZmZkOWYwMWExOSIsImlhdCI6MTczNjQwNDQ0MCwiZXhwIjoxNzM2NDA4MDQwfQ.0YHNrCJs97TL4651X9PXmUJpDL5i-2ObFuBtKWqnmSM
Content-Type: application/json

{
    "message": "Created Post",
    "sender": "Not",
    "userId": "677e243ededa7fffd9f01a19"
}

### Get all posts
GET http://localhost:3000/post

### Get a post by id
Get http://localhost:3000/post/6778228f5d3ff79bcdbb71f3

### Get all posts by a sender
Get http://localhost:3000/post?sender=Not

### Update a post by id
PUT http://localhost:3000/post/6778228f5d3ff79bcdbb71f3
Content-Type: application/json

{
    "message": "Updated Post",
    "sender": "Rotem"
}



#### Comments API

### Get comment by id
GET http://localhost:3000/comment/67782e9f5eee8c76935142f7


#### Get comments by post id
GET http://localhost:3000/comment?post_id=67782e9b5eee8c76935142f5


### Create a comment
POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "67782e9b5eee8c76935142f5",
    "content": "content",
    "senderId": "test-id2"
}


### Update comment
PUT http://localhost:3000/comment/67782e9f5eee8c76935142f7
Content-Type: application/json

{
    "content": "new comment content"
}


### Delete comment by id
DELETE http://localhost:3000/comment/67782e9f5eee8c76935142f7



### Register new user
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "Amit",
    "username": "test",
    "email": "test@test.test",
    "password": "123456"
}


### Login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "test",
    "password": "123456"
}


### Logout
POST http://localhost:3000/user/logout
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UyNDNlZGVkYTdmZmZkOWYwMWExOSIsImlhdCI6MTczNjMyMDIwOH0.sujoZsKazY1dWO8GzkLVxKSbsYmd5cowZMh6p3XvjkQ

### Refresh Token
POST http://localhost:3000/user/refreshToken
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2UyNDNlZGVkYTdmZmZkOWYwMWExOSIsImlhdCI6MTczNjMyMDI3MH0.nyW6rPp1ik0E413F0RIuTmrbM1QTS-9Igmt7-GRmO78
